"""ARQ task for generating AI auto-fix PRs."""

from uuid import UUID

from sqlalchemy import select

from core.logging import get_logger
from db.engine import async_session
from db.models.finding import Finding
from db.models.repo import Repo
from db.models.organization import Organization
from services.auto_fix import (
    get_file_from_github,
    generate_fix_with_claude,
    create_branch,
    commit_file,
    create_pull_request,
)
from services.github import get_installation_token

logger = get_logger(__name__)


async def run_auto_fix(ctx: dict, finding_id: str) -> None:
    """Generate an AI fix and open a PR for a finding."""
    logger.info("auto_fix_started", finding_id=finding_id)

    async with async_session() as db:
        finding = (
            await db.execute(select(Finding).where(Finding.id == UUID(finding_id)))
        ).scalar_one_or_none()
        if not finding:
            logger.error("finding_not_found", finding_id=finding_id)
            return

        repo = (
            await db.execute(select(Repo).where(Repo.id == finding.repo_id))
        ).scalar_one()
        org = (
            await db.execute(select(Organization).where(Organization.id == repo.org_id))
        ).scalar_one()

        # Mark as in_progress
        finding.auto_fix_status = "in_progress"
        await db.commit()

    try:
        # Get GitHub installation token
        token = await get_installation_token(org.installation_id)

        # Fetch the file from GitHub
        file_content, blob_sha = await get_file_from_github(
            token, repo.full_name, finding.file_path, repo.default_branch,
        )

        # Determine language from file extension
        ext = finding.file_path.rsplit(".", 1)[-1] if "." in finding.file_path else ""
        lang_map = {
            "py": "python", "js": "javascript", "ts": "typescript",
            "tsx": "typescript", "jsx": "javascript", "go": "go",
            "java": "java", "rb": "ruby", "rs": "rust", "c": "c",
            "cpp": "cpp", "cs": "csharp", "php": "php",
        }
        language = lang_map.get(ext, ext)

        # Generate fix with Claude
        fixed_content = await generate_fix_with_claude(
            finding_title=finding.title,
            finding_severity=finding.severity,
            finding_category=finding.category,
            finding_rule_id=finding.rule_id,
            finding_file_path=finding.file_path,
            finding_line_start=finding.line_start,
            finding_description=finding.description,
            finding_suggested_fix=finding.ai_suggested_fix,
            file_content=file_content,
            language=language,
        )

        # Validate fix differs from original
        if fixed_content.strip() == file_content.strip():
            raise ValueError("Generated fix is identical to original file")

        # Create branch, commit, and PR
        branch_name = f"spectra/fix-{finding_id[:8]}"
        await create_branch(token, repo.full_name, branch_name, repo.default_branch)

        commit_msg = f"fix: {finding.title}\n\nAuto-fix generated by Spectra AI for {finding.rule_id}"
        await commit_file(
            token, repo.full_name, finding.file_path,
            fixed_content, blob_sha, branch_name, commit_msg,
        )

        pr_body = (
            f"## Spectra Auto-Fix\n\n"
            f"**Finding:** {finding.title}\n"
            f"**Severity:** {finding.severity}\n"
            f"**Rule:** `{finding.rule_id}`\n"
            f"**File:** `{finding.file_path}:{finding.line_start or ''}`\n\n"
            f"### AI Explanation\n{finding.ai_explanation or 'N/A'}\n\n"
            f"### Suggested Fix\n```\n{finding.ai_suggested_fix or 'N/A'}\n```\n\n"
            f"---\n*Auto-generated by [Spectra](https://github.com/apps/spectra-security)*"
        )

        pr_data = await create_pull_request(
            token, repo.full_name,
            f"fix: {finding.title}",
            pr_body, branch_name, repo.default_branch,
        )

        # Update finding with PR info
        async with async_session() as db:
            f = (await db.execute(select(Finding).where(Finding.id == UUID(finding_id)))).scalar_one()
            f.auto_fix_status = "pr_created"
            f.auto_fix_pr_url = pr_data["html_url"]
            f.auto_fix_pr_number = pr_data["number"]
            f.auto_fix_error = None
            await db.commit()

        logger.info("auto_fix_completed", finding_id=finding_id, pr_url=pr_data["html_url"])

    except Exception as e:
        logger.exception("auto_fix_failed", finding_id=finding_id)
        async with async_session() as db:
            f = (await db.execute(select(Finding).where(Finding.id == UUID(finding_id)))).scalar_one()
            f.auto_fix_status = "failed"
            f.auto_fix_error = str(e)
            await db.commit()
